services:
  - type: web
    name: astral-sudba-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyAOskxKqsmk718oCtgcXS1fW4yBCOy90Wo
      - key: SUPABASE_URL
        value: https://hkurtoonrpxnrspmuzgt.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_G3X4bzQpmaQ-GRjMRvQhhw_ft3Feab9
